name: to_do_application
description: "A TODO App for internship assignment at ebPearls using Flutter, Bloc, and Hive."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For iOS-style icons (used in both iOS and Android)
  cupertino_icons: ^1.0.8

  # ------------------------------
  # STATE MANAGEMENT
  # ------------------------------
  flutter_bloc: ^8.1.3           # For managing app logic using Bloc pattern
  equatable: ^2.0.5              # Helps compare Bloc states easily (value-based equality)

  # ------------------------------
  # LOCAL STORAGE
  # ------------------------------
  hive: ^2.2.3                   # Lightweight key-value database for storing tasks
  hive_flutter: ^1.1.0           # Adds Flutter support to Hive (like directory path setup)
  path_provider: ^2.1.2          # Required to get the application directory for Hive storage

  # ------------------------------
  # UTILITIES
  # ------------------------------
  uuid: ^4.1.0                   # For generating unique task IDs
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0          # Standard lint rules to keep your code clean and consistent

  # ------------------------------
  # CODE GENERATION (for Hive)
  # ------------------------------
  build_runner: ^2.4.8           # Runs code generators (for HiveAdapter)
  hive_generator: ^2.0.1         # Generates Hive TypeAdapter for your models

flutter:
  uses-material-design: true     # Enables material design icons and components

  # If you want to add images or fonts in the future, you'd define them like this:
  assets:
    - assets/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
